// <auto-generated />
namespace CMSController.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MAKE_NUMBER_AS_LONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAKE_NUMBER_AS_LONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201704271312211_MAKE_NUMBER_AS_LONG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
